

export const LOAD_RIDES = "LOAD_RIDES"
export const SEARCH_CHARACTERS = "SEARCH_CHARACTERS"
export const FILTER_RIDES = "FILTER_RIDES"
export const ADD_TO_CART = "ADD_TO_CART"
export const LOAD_RESOURCES="LOAD_RESOURCES"
export const FILTER_RESOURCES = "FILTER_RESOURCES"